title:              "Loading Blog"
tagline:            "ë§ˆì¼€íŒ…ì„ ê²Œì„ì²˜ëŸ¼ ì‰½ê²Œ ğŸ•¹ï¸"
email:              "ndk0929@gmail.com"
description:        "ë§ˆì¼€íŒ… ì •ë³´ë¥¼ ê²Œì„ì²˜ëŸ¼ ì‰½ê²Œ ì•Œë ¤ì£¼ëŠ” ë¸”ë¡œê·¸ (ê³µì‹ê´‘ê³ /ë°”ì´ëŸ´ê´‘ê³ /ë°ì´í„°ë¶„ì„/ë§ˆì¼€íŒ…ì •ë³´ê³µìœ )"
author:             "Loading"
baseurl:            ""
url:                "https://loading.kr"
locale:             "ko_KR"
thumbnail:          "/img/smain.png"

# Social Profiles
instagram_username: nohdk777
facebook_username:  100010201817907
linkedin_username:  ë™ê·œ-ë…¸-478872155

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
# ë¸”ë¡œê·¸ disqus shortname
disqus:
  shortname: loading-kr
